package models

type Food struct {
	Name     string
	Price    int
	Category string
}

var FoodList = []Food{
	{Name: "Nasi Goreng Kampung", Price: 15000, Category: "Meals"},
	{Name: "Mie Ayam Wonogiri", Price: 14000, Category: "Meals"},
	{Name: "Soto Betawi", Price: 20000, Category: "Meals"},
	{Name: "Ketoprak Cirebon", Price: 12000, Category: "Meals"},
	{Name: "Bakso Malang", Price: 17000, Category: "Meals"},
	{Name: "Ayam Geprek", Price: 18000, Category: "Meals"},
	{Name: "Nasi Uduk Jakarta", Price: 13000, Category: "Meals"},
	{Name: "Gado-Gado", Price: 15000, Category: "Meals"},
	{Name: "Sate Ayam Madura", Price: 20000, Category: "Meals"},
	{Name: "Rawon Surabaya", Price: 22000, Category: "Meals"},
	{Name: "Nasi Pecel Madiun", Price: 14000, Category: "Meals"},
	{Name: "Lontong Sayur", Price: 16000, Category: "Meals"},
	{Name: "Nasi Kuning Manado", Price: 18000, Category: "Meals"},
	{Name: "Rendang Padang", Price: 25000, Category: "Meals"},
	{Name: "Sop Buntut", Price: 30000, Category: "Meals"},
	{Name: "Ikan Bakar Jimbaran", Price: 28000, Category: "Meals"},
	{Name: "Nasi Campur Bali", Price: 20000, Category: "Meals"},
	{Name: "Tahu Telor", Price: 12000, Category: "Meals"},
	{Name: "Ayam Penyet", Price: 17000, Category: "Meals"},
	{Name: "Nasi Liwet Solo", Price: 19000, Category: "Meals"},

	{Name: "Es Teh Kampul", Price: 4000, Category: "Drinks"},
	{Name: "Es Jeruk Liar", Price: 5000, Category: "Drinks"},
	{Name: "Jus Terong Belanda", Price: 8000, Category: "Drinks"},
	{Name: "Air Kelapa", Price: 6000, Category: "Drinks"},
	{Name: "Air Putih Anget", Price: 1000, Category: "Drinks"},
	{Name: "Es Kopi Susu", Price: 10000, Category: "Drinks"},
	{Name: "Teh Tarik", Price: 7000, Category: "Drinks"},
	{Name: "Jus Alpukat", Price: 12000, Category: "Drinks"},
	{Name: "Es Cincau", Price: 6000, Category: "Drinks"},
	{Name: "Soda Gembira", Price: 9000, Category: "Drinks"},
	{Name: "Es Buah", Price: 15000, Category: "Drinks"},
	{Name: "Wedang Jahe", Price: 8000, Category: "Drinks"},
	{Name: "Jus Mangga", Price: 10000, Category: "Drinks"},
	{Name: "Es Kelapa Muda", Price: 12000, Category: "Drinks"},
	{Name: "Milkshake Coklat", Price: 15000, Category: "Drinks"},
	{Name: "Es Teh Manis", Price: 5000, Category: "Drinks"},
	{Name: "Jus Tomat", Price: 8000, Category: "Drinks"},
	{Name: "Lemon Tea", Price: 7000, Category: "Drinks"},
	{Name: "Es Lidah Buaya", Price: 10000, Category: "Drinks"},
	{Name: "Smoothie Strawberry", Price: 18000, Category: "Drinks"},

	{Name: "Kacang Atom", Price: 3000, Category: "Snacks"},
	{Name: "Kerupuk Jangek", Price: 5000, Category: "Snacks"},
	{Name: "Otak-otak", Price: 2000, Category: "Snacks"},
	{Name: "Peyek", Price: 4000, Category: "Snacks"},
	{Name: "Gorengan", Price: 1500, Category: "Snacks"},
	{Name: "Tempe Mendoan", Price: 3000, Category: "Snacks"},
	{Name: "Cireng", Price: 4000, Category: "Snacks"},
	{Name: "Batagor", Price: 7000, Category: "Snacks"},
	{Name: "Siomay", Price: 6000, Category: "Snacks"},
	{Name: "Risol Mayo", Price: 5000, Category: "Snacks"},
	{Name: "Lumpia Semarang", Price: 8000, Category: "Snacks"},
	{Name: "Tahu Isi", Price: 3000, Category: "Snacks"},
	{Name: "Bakwan Jagung", Price: 4000, Category: "Snacks"},
	{Name: "Keripik Singkong", Price: 5000, Category: "Snacks"},
	{Name: "Emping Melinjo", Price: 6000, Category: "Snacks"},
	{Name: "Kue Cubit", Price: 4000, Category: "Snacks"},
	{Name: "Pastel", Price: 5000, Category: "Snacks"},
	{Name: "Keripik Tempe", Price: 7000, Category: "Snacks"},
	{Name: "Tahu Gejrot", Price: 6000, Category: "Snacks"},
	{Name: "Cilok", Price: 3000, Category: "Snacks"},

	{Name: "Es Krim Xue", Price: 19000, Category: "Desserts"},
	{Name: "Cendol Dawet", Price: 15000, Category: "Desserts"},
	{Name: "Martabak Mesir", Price: 20000, Category: "Desserts"},
	{Name: "Coklat Dubai", Price: 60000, Category: "Desserts"},
	{Name: "Mango Sago", Price: 30000, Category: "Desserts"},
	{Name: "Kue Lapis", Price: 10000, Category: "Desserts"},
	{Name: "Puding Coklat", Price: 12000, Category: "Desserts"},
	{Name: "Klepon", Price: 5000, Category: "Desserts"},
	{Name: "Onde-Onde", Price: 6000, Category: "Desserts"},
	{Name: "Bika Ambon", Price: 25000, Category: "Desserts"},
	{Name: "Kue Putu", Price: 4000, Category: "Desserts"},
	{Name: "Serabi Solo", Price: 8000, Category: "Desserts"},
	{Name: "Es Teler", Price: 15000, Category: "Desserts"},
	{Name: "Kolplay", Price: 12000, Category: "Desserts"},
	{Name: "Kue Sus", Price: 7000, Category: "Desserts"},
	{Name: "Bolu Kukus", Price: 10000, Category: "Desserts"},
	{Name: "Lemper", Price: 6000, Category: "Desserts"},
	{Name: "Pancake Durian", Price: 20000, Category: "Desserts"},
	{Name: "Wajik", Price: 8000, Category: "Desserts"},
	{Name: "Dodol Garut", Price: 15000, Category: "Desserts"},
}